USE DBA_Inventory
select SERVERNAME from 
[dbo].[DBA_Infrastructure]
where servername not in 
(
'MIABDSCOSSQL01\OGTM',
'MIABDSCOSSQL01\PCOPY',
'MIAPDODSSQL01',
'RHPSCOSSQL03',
'MIABDSCOSSQL01\QS',
'RHPSCOSSQLCLU',
'RHPBPERAPP01',
'RHPVPSCLSQLCLU',
'RSSVACCELLOS01',
'MIABTHYPSQL',
'MIABDEVHYPSQL',
'MIARDRCLUDBA',
'MIAVQFMSSQL01\SSCB_DEV',
'SSCBPHYPDBA',
'MIAVPEXOPTS02',
'SSCVPIDERA01',
'MIAPPAMDATADB'
)
